version: "3"

tasks:
  init:
    - echo "init"

  run:
    cmds:
      - cargo run

  test:
    cmds:
      - cargo test

  release:
    cmds:
      - cargo build --release
      - cd ../..; open target/release/

  install:
    cmds:
      - echo "install the local build binary to ~/.cargo/bin."
      - cargo install --path . --force --verbose
      - cargo install --list
      - cd ../..; open target/release/

  clean:
    cmds:
      - cargo clean

  publish:dry:
    cmds:
      - cargo publish --dry-run


  publish:
    cmds:
      - cargo publish

  publish:check:
    cmds:
      - cargo package --list